method: RhoLoss
method_opt:
  ratio: 0.1
  balance: False
  ratio_scheduler: constant
  warmup_epochs: 0
  uniform_epochs: 0

teacher_model_source: clip # Supported options: "local_pretrained", "clip", "timm"
# teacher_model_path: ./models/teacher/MNIST.tar
# teacher_model_path: ./exp/cifar10_small-cnn_30-epoch.tar

# If local_pretrained is selected, specify the model architecture here
# local_pretrained:
#   type: LeNet
#   params: 
#     m_type: 'lenet'

# If Clip is selected, specify the model architecture here
clip:
  clip_architecture: 'RN50'
  tau: 4
