# Config template to be used with `generate_configs.py`. Trains a ResNet model
# on CIFAR3 (dog, cat, bird) using a ResNet model using Uniform batch selection.
# Searches over learning rates.

run_name_format:
  - example
  - $dataset.name
  - $training_opt.optimizer
  - lr: [$training_opt.optim_params.lr]

seed: __REQUIRED__ # To be set to an int

dataset:
  name: CIFAR3
  root: ./_CIFAR
  num_classes: 3
  im_size: [32, 32]
  in_channels: 3
  input_dim: [1, 3, 32, 32]

networks:
  type: ResNet_torchvision
  params:
    m_type: 'resnet18'

training_opt:
  num_epochs: 100
  num_data_workers: 1
  batch_size: 320
  test_batch_size: 512
  optimizer: __REQUIRED__ # To be set as SGD or AdamW
  optim_params:
    lr: __REQUIRED__ # To be set to a float
    weight_decay: 0.0005
  scheduler_params: {}
  scheduler: 'constant'
  loss_type: CrossEntropy
  loss_params: {}

method: Uniform
method_opt:
  ratio: 1.0
  balance: False
  ratio_scheduler: constant
  warmup_epochs: 0

diagnostics:
  logging_defaults:
    log_interval: logarithmic
    save_init: 5
    save_freq: 4
  diagnostics:
    - TrainLoss: {}
    - TrainAcc: {}
    - ValLoss: {}
    - ValAcc: {}
    - Timing: {}
    - Checkpoint: {}

wandb:
  project: "Example" 
  mode: online
