training_opt:
  num_epochs: 500
  # num_steps: 100000
  num_data_workers: 1
  batch_size: 320
  test_batch_size: 512
  optimizer: SGD
  optim_params:
    lr: 0.01
    weight_decay: 0.01
  scheduler_params: {}
  scheduler: 'constant'

  loss_type: CrossEntropy
  loss_params: {}