method: Bayesian
method_opt:
  ratio: 0.1
  balance: False
  ratio_scheduler: constant
  warmup_epochs: 0

# Online Laplace Approximation Parameters
adaptive_alpha: False
alpha: 0.2
prior_precision: 10
num_effective_data: 200
laplace_momentum: 0.99
n_f_samples: 256


teacher_model_source: clip # Supported options: "local_pretrained", "clip", "timm"
# teacher_model_path: /home/lgreen/projects/Online_BS/models/teacher/MakeBlobs.tar
# teacher_model_path: /home/phancock/Online-Batch-Selection/exp/cifar10_small-cnn_30-epoch.tar

# If local_pretrained is selected, specify the model architecture here
# local_pretrained:
#   type: Small_cnn
#   params: 
#     m_type: 'Small_cnn'

# If Clip is selected, specify the model architecture here
clip:
  clip_architecture: 'ViT-B/16'
  tau: 4
